# Generated by Django 2.0.2 on 2018-02-22 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('canceled', 'Canceled')], max_length=64)),
                ('date', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete='Cascade', to='customer.Customer')),
                ('product', models.ForeignKey(on_delete='Cascade', to='product.Product')),
            ],
        ),
    ]
